spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 10.211.55.6
    port: 6379
server:
  port: 20000