spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.77.177:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.77.177:8848
  application:
    name: mall-order
  rabbitmq:
    addresses: 192.168.77.177
    port: 5672
    virtual-host: /
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.77.177
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
